classdef SimulationDataTest < matlab.unittest.TestCase
    
    methods(Test)
        function correlationAndMeanTest(testCase)
            p = uint64(5);
            q = uint64(3);
            rho = 0.5;
            n = uint64(10000);
            response_func = @(X, Z) ...
                ( ...
                    X(:,2) + X(:,4) + ...
                    sqrt(2) * sin(pi * Z(:,1)) ...
                )';
            noise_std_dev = 1;
            data = ...
                SimulationData( ...
                    p, ...
                    q, ...
                    rho, ...
                    n, ...
                    response_func, ...
                    noise_std_dev ...
                );
            tol = 1e-1;
            mu_X1 = mean(data.X(:,1));
            mu_X2 = mean(data.X(:,2));
            mu_X3 = mean(data.X(:,3));
            mu_X4 = mean(data.X(:,4));
            mu_X5 = mean(data.X(:,5));
            X_means = [mu_X1 mu_X2 mu_X3 mu_X4 mu_X5];
            testCase.verifyTrue(all(abs(X_means - 0) < tol));
            covariance_X = cov(data.X);
            testCase.verifyTrue( ...
                abs(covariance_X(1,1) - rho ^ abs(1 - 1)) ...
                < tol ...
            );
            testCase.verifyTrue( ...
                abs(covariance_X(1,2) - rho ^ abs(1 - 2)) ...
                < tol ...
            );
            testCase.verifyTrue( ...
                abs(covariance_X(3,5) - rho ^ abs(3 - 5)) ...
                < tol ...
            );
        end
    end
    
end